import { Injectable } from "@angular/core";

export interface TypeInfo {
  weakTo: string[];
  strongAgainst: string[];
  notVeryEffectiveAgainst: string[];
  noEffectAgainst: string[];
  resists: string[];
  immuneTo: string[];
}

@Injectable()
export class DexService {
  typeData: Record<string, TypeInfo> = {
    Normale: {
      weakTo: ["Lotta"],
      strongAgainst: [],
      notVeryEffectiveAgainst: ["Roccia", "Acciaio"],
      noEffectAgainst: ["Spettro"],
      resists: [],
      immuneTo: ["Spettro"],
    },
    Fuoco: {
      weakTo: ["Acqua", "Terra", "Roccia"],
      strongAgainst: ["Erba", "Ghiaccio", "Coleottero", "Acciaio"],
      notVeryEffectiveAgainst: ["Fuoco", "Acqua", "Roccia", "Drago"],
      noEffectAgainst: [],
      resists: [
        "Fuoco",
        "Erba",
        "Ghiaccio",
        "Coleottero",
        "Acciaio",
        "Folletto",
      ],
      immuneTo: [],
    },
    Acqua: {
      weakTo: ["Erba", "Elettro"],
      strongAgainst: ["Fuoco", "Terra", "Roccia"],
      notVeryEffectiveAgainst: ["Acqua", "Erba", "Drago"],
      noEffectAgainst: [],
      resists: ["Fuoco", "Acqua", "Ghiaccio", "Acciaio"],
      immuneTo: [],
    },
    Erba: {
      weakTo: ["Fuoco", "Ghiaccio", "Veleno", "Volante", "Coleottero"],
      strongAgainst: ["Acqua", "Terra", "Roccia"],
      notVeryEffectiveAgainst: [
        "Fuoco",
        "Erba",
        "Veleno",
        "Volante",
        "Coleottero",
        "Drago",
        "Acciaio",
      ],
      noEffectAgainst: [],
      resists: ["Acqua", "Erba", "Elettro", "Terra"],
      immuneTo: [],
    },
    Elettro: {
      weakTo: ["Terra"],
      strongAgainst: ["Acqua", "Volante"],
      notVeryEffectiveAgainst: ["Erba", "Elettro", "Drago"],
      noEffectAgainst: [],
      resists: ["Elettro", "Volante", "Acciaio"],
      immuneTo: [],
    },
    Ghiaccio: {
      weakTo: ["Fuoco", "Lotta", "Roccia", "Acciaio"],
      strongAgainst: ["Erba", "Terra", "Volante", "Drago"],
      notVeryEffectiveAgainst: ["Fuoco", "Acqua", "Ghiaccio", "Acciaio"],
      noEffectAgainst: [],
      resists: ["Ghiaccio"],
      immuneTo: [],
    },
    Lotta: {
      weakTo: ["Volante", "Psico", "Folletto"],
      strongAgainst: ["Normale", "Ghiaccio", "Roccia", "Buio", "Acciaio"],
      notVeryEffectiveAgainst: [
        "Veleno",
        "Volante",
        "Psico",
        "Coleottero",
        "Folletto",
      ],
      noEffectAgainst: [],
      resists: ["Coleottero", "Roccia", "Buio"],
      immuneTo: [],
    },
    Veleno: {
      weakTo: ["Terra", "Psico"],
      strongAgainst: ["Erba", "Folletto"],
      notVeryEffectiveAgainst: ["Veleno", "Terra", "Roccia", "Spettro"],
      noEffectAgainst: [],
      resists: ["Erba", "Lotta", "Veleno", "Coleottero", "Folletto"],
      immuneTo: [],
    },
    Terra: {
      weakTo: ["Acqua", "Erba", "Ghiaccio"],
      strongAgainst: ["Fuoco", "Elettro", "Veleno", "Roccia", "Acciaio"],
      notVeryEffectiveAgainst: ["Erba", "Coleottero"],
      noEffectAgainst: [],
      resists: ["Veleno", "Roccia"],
      immuneTo: ["Elettro"],
    },
    Volante: {
      weakTo: ["Elettro", "Ghiaccio", "Roccia"],
      strongAgainst: ["Erba", "Lotta", "Coleottero"],
      notVeryEffectiveAgainst: ["Elettro", "Roccia", "Acciaio"],
      noEffectAgainst: [],
      resists: ["Erba", "Lotta", "Coleottero"],
      immuneTo: ["Terra"],
    },
    Psico: {
      weakTo: ["Coleottero", "Spettro", "Buio"],
      strongAgainst: ["Lotta", "Veleno"],
      notVeryEffectiveAgainst: ["Psico", "Acciaio"],
      noEffectAgainst: [],
      resists: ["Lotta", "Psico"],
      immuneTo: [],
    },
    Coleottero: {
      weakTo: ["Fuoco", "Volante", "Roccia"],
      strongAgainst: ["Erba", "Psico", "Buio"],
      notVeryEffectiveAgainst: [
        "Fuoco",
        "Lotta",
        "Veleno",
        "Volante",
        "Spettro",
        "Drago",
        "Acciaio",
        "Folletto",
      ],
      noEffectAgainst: [],
      resists: ["Erba", "Lotta", "Terra"],
      immuneTo: [],
    },
    Roccia: {
      weakTo: ["Acqua", "Erba", "Lotta", "Terra", "Acciaio"],
      strongAgainst: ["Fuoco", "Ghiaccio", "Volante", "Coleottero"],
      notVeryEffectiveAgainst: ["Lotta", "Terra", "Acciaio"],
      noEffectAgainst: [],
      resists: ["Normale", "Fuoco", "Veleno", "Volante"],
      immuneTo: [],
    },
    Spettro: {
      weakTo: ["Spettro", "Buio"],
      strongAgainst: ["Psico", "Spettro"],
      notVeryEffectiveAgainst: ["Buio"],
      noEffectAgainst: [],
      resists: ["Veleno", "Coleottero"],
      immuneTo: ["Normale", "Lotta"],
    },
    Drago: {
      weakTo: ["Ghiaccio", "Drago", "Folletto"],
      strongAgainst: ["Drago"],
      notVeryEffectiveAgainst: ["Acciaio"],
      noEffectAgainst: [],
      resists: ["Fuoco", "Acqua", "Erba", "Elettro"],
      immuneTo: [],
    },
    Buio: {
      weakTo: ["Lotta", "Coleottero", "Folletto"],
      strongAgainst: ["Psico", "Spettro"],
      notVeryEffectiveAgainst: ["Lotta", "Buio", "Folletto"],
      noEffectAgainst: [],
      resists: ["Spettro", "Buio"],
      immuneTo: ["Psico"],
    },
    Acciaio: {
      weakTo: ["Fuoco", "Lotta", "Terra"],
      strongAgainst: ["Ghiaccio", "Roccia", "Folletto"],
      notVeryEffectiveAgainst: ["Fuoco", "Acqua", "Elettro", "Acciaio"],
      noEffectAgainst: [],
      resists: [
        "Normale",
        "Erba",
        "Ghiaccio",
        "Volante",
        "Psico",
        "Coleottero",
        "Roccia",
        "Drago",
        "Acciaio",
        "Folletto",
      ],
      immuneTo: ["Veleno"],
    },
    Folletto: {
      weakTo: ["Veleno", "Acciaio"],
      strongAgainst: ["Lotta", "Drago", "Buio"],
      notVeryEffectiveAgainst: ["Fuoco", "Veleno", "Acciaio"],
      noEffectAgainst: [],
      resists: ["Lotta", "Coleottero", "Buio"],
      immuneTo: ["Drago"],
    },
  };

  typeColors: Record<string, string> = {
    Normale: "#A8A77A",
    Fuoco: "#EE8130",
    Acqua: "#6390F0",
    Erba: "#7AC74C",
    Elettro: "#F7D02C",
    Ghiaccio: "#96D9D6",
    Lotta: "#C22E28",
    Veleno: "#A33EA1",
    Terra: "#E2BF65",
    Volante: "#A98FF3",
    Psico: "#F95587",
    Coleottero: "#A6B91A",
    Roccia: "#B6A136",
    Spettro: "#735797",
    Drago: "#6F35FC",
    Buio: "#705746",
    Acciaio: "#B7B7CE",
    Folletto: "#D685AD",
  };

  typeOrder: string[] = [
    "Normale",
    "Lotta",
    "Fuoco",
    "Acqua",
    "Erba",
    "Elettro",
    "Ghiaccio",
    "Psico",
    "Buio",
    "Drago",
    "Acciaio",
    "Folletto",
    "Volante",
    "Veleno",
    "Terra",
    "Roccia",
    "Coleottero",
    "Spettro",
  ];
}
